default: &default
  adapter: postgresql
  encoding: unicode
  database: railsblogapplication_production
  username: postgres
  password: 1458
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: railsblogapplication

#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  <<: *default
  database: railsblogapplication_production
  username: postgres
  password: <%= ENV["RAILSBLOGAPPLICATION_DATABASE_PASSWORD"] %>
